### ISSUE TITLE
Missed app.use statement

### ISSUE THREAD

**Issue by MaratOM** [eXtremeXR/APIAuthenticationWithNode#9]
There is no 

app.use(bodyParser.urlencoded({
  extended: true
}));

statement in app.js

**Comment by gpedro34** [comment]
@eXtremeXR [bodyParser was actually integrated into express in version 4.16.0](https://stackoverflow.com/questions/47232187/express-json-vs-bodyparser-json/47232318#47232318) so should be:

```js
app.use(express.json()); // CHANGE
```
instead of 
```js
app.use(bodyParser.json());
```

And remove bodyParser dependency :smiley: 

---

Regarding the OP issue, [I'm not really sure if you need it](https://stackoverflow.com/a/45690436) but in case you do, the new form:
```js
app.use(express.urlencoded({ extended: false })); //ADD
```

Thank you for the videos man, have been really helpful :wink:

**Comment by eXtremeXR** [comment]
Thanks for the detailed reply @gpedro34 ! Also thanks for the kind words 🙂 😉 
Will merge your PR!

**Comment by gpedro34** [comment]
Thanks @eXtremeXR ... This is one of my first PRs so I'm glad it got merged...  
Just noticed the changes my standard Prettier config did to some files.  
You should re-enforce your EditorConfig in those files, sorry  
See you around  :wink:
